create or replace view `{{params.project_id}}.{{params.dataset}}.responses` as
    with lastest_responses as 
    (
        select response_id as rid ,max(_sync_unix_timestamp) as max_sync_unix_timestamp from `{{params.project_id}}.{{params.dataset}}._raw_snapshot_responses` group by 1
    )
    select 
    _sync_unix_timestamp,
    DATETIME(TIMESTAMP_SECONDS(_sync_unix_timestamp),"America/New_York") as _sync,
    cast(response_id as int64) as response_id,
    cast(person_id as int64) as person_id,
    name,
    email,
    cast(answer as int64) as answer,
    cast(answerlabel as int64) as answerlabel,
    data,
    comment,
    note,
    status,
    dontcontact,
    cast(sent as int64) as sent_unix_timestamp,
    cast(opened as int64)  as opened_unix_timestamp,
    cast(responded as int64) as responded_unix_timestamp,
    cast(lastemailed as int64) as lastemailed_unix_timestamp,
    cast(created as int64) as created_unix_timestamp,
    DATETIME(TIMESTAMP_SECONDS(cast(sent as int64)),"America/New_York") as sent,
    DATETIME(TIMESTAMP_SECONDS(cast(opened as int64)),"America/New_York")  as opened,
    DATETIME(TIMESTAMP_SECONDS(cast(responded as int64)),"America/New_York") as responded,
    DATETIME(TIMESTAMP_SECONDS(cast(lastemailed as int64)),"America/New_York") as lastemailed,
    DATETIME(TIMESTAMP_SECONDS(cast(created as int64)),"America/New_York") as created,
    segment,
    question_type,
    published,
    publishedname,
    publishedavatar,
    deliverymethod,
    survey_template,
    theme,
    life_cycle,
    product_type_c,
    city_name_c,
    region_name_c,
    country_name_c,
    timezone_c,
    cast(orderid_c as int64) as orderid_c,
    currency_c,
    cast(spend_c as float64) as spend_c,
    product_c,
    province_c,
    city_c,
    country_c,
    cast(orders_made_c as int64) as orders_made_c,
    cast(lifetime_spend_c as float64) as lifetime_spend_c,
    customer_tags_c,
    shipping_c,
    topic_c,
    workflow_follow_up_blank_comm_c,
    kustomer_conversationid_c,
    workflow_kustomer_c,
    dashboard,
    email_token
    from `{{params.project_id}}.{{params.dataset}}._raw_snapshot_responses` r
    right join lastest_responses lr on lr.max_sync_unix_timestamp = r._sync_unix_timestamp and lr.rid = r.response_id
    order by greatest(
        coalesce( sent_unix_timestamp ,0),
        coalesce( opened_unix_timestamp,0),
        coalesce( responded_unix_timestamp,0),
        coalesce( lastemailed_unix_timestamp,0),
        coalesce( created_unix_timestamp,0)) desc